@startuml proyectoDandi
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Enterprise_Boundary(empresa, "LDVR") {

        Person(usuario, "Usuario", "Usuario de la aplicación móvil", SPRITE_ANDROID)
    System_Boundary(sistema, "Sistema de Aplicación Móvil") {

        Container_Boundary(aplicacion_movil,"Aplicación Móvil"){
            Component(logica,"logica de aplicacion","JAVA","logica de aplicacion")
            Component(vista,"interfaz de aplicacion","XML","UI de aplicación")
        }

        Container_Boundary(firebase,"Firebase"){
            Component(firestore,"base de datos","JSON","se almacenan los datos del usuario")
            Component(eventos,"disparador de eventos","Triggers","emite eventos a los usuarios de un grupo ")
        }

    }
}

Rel_D(usuario,vista,"interacción de usuario")
Rel_U(vista,usuario,"muestra datos nuevos")
Rel_D(vista,logica,"eventos de usuario")
Rel_U(logica,vista,"actualizacion de información en vista")
Rel_D(logica,firestore,"actualización de estadísticas")
Rel_U(firestore,logica,"emite datos actualizados")
Rel_U(eventos,logica,"evento recibido")
Rel_D(logica,eventos,"evento emitido")

@enduml