@startuml proyectoDandi
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Enterprise_Boundary(empresa, "LDVR") {
    System_Boundary(sistema, "Sistema de Aplicación Móvil") {

        Person(usuario, "Usuario", "Usuario de la aplicación móvil", SPRITE_ANDROID)

        Container_Boundary(aplicacion_movil,"Aplicación Móvil"){
            Component(logica,"logica de aplicacion","JAVA","logica de aplicacion")
            Component(vista,"interfaz de aplicacion","XML","UI de aplicación")
        }

        Container_Boundary(firebase,"Firebase"){
            Component(firestore,"base de datos","JSON","se almacenan los datos del usuario")
            Component(notificaciones,"disparador de eventos","Triggers","emite eventos a los usuarios de un grupo ")
        }

    }
}

BiRel(usuario,vista,"interacción de usuario")
Rel_D(vista,logica,"eventos de usuario")
BiRel(vista,logica,"actualizacion de estadísticas")
BiRel(vista,logica,"recepción/emisión de eventos")

@enduml