@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


!define FONTAWESOME6 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons/font-awesome-6
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons/devicons

!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons/devicons2
!define MATERIAL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons/material


!include FONTAWESOME6/users.puml
!include FONTAWESOME6/school.puml
!include FONTAWESOME6/certificate.puml
!include FONTAWESOME6/android.puml
!include FONTAWESOME6/cube.puml


!include FONTAWESOME6/windows.puml
!include DEVICONS/html5.puml
!include DEVICONS/python.puml
!include DEVICONS/mysql.puml
!include DEVICONS2/flask_original.puml

!include MATERIAL/web.puml
!include MATERIAL/person.puml
!include DEVICONS2/angular.puml

LAYOUT_WITH_LEGEND()

  System(app2, "Usuario", "El usuario interactua con la pagina", $sprite="person")

Enterprise_Boundary(c1, "Modulo de Categorias") {
    System(app, "Sistema de Gestión de Categorías", "Sistema para la creación, modificación y visualización de categorías de eventos.", $sprite="web")


    System_Boundary(c2, "Contenedores") {
        ContainerDb(bd, "Base de Datos - Categorías", "MySQL", "Almacena la tabla 'categorias' con los datos de cada categoría.", $sprite="mysql")
        Container(api, "API de Categorías", "Python/Flask", "Servicio para crear, buscar y actualizar categorías.", $sprite="python")

        Container_Boundary(c3, "Componentes del API") {
            Component(Flask, "app.py", "Flask", "Endpoints y lógica CRUD para el módulo de categorías.", $sprite="flask_original")
        }

        Container(html, "Front-end (HTML)", "HTML5", "Formularios y vistas para listar y administrar categorías.", $sprite="html5")
        Container(angular, "Frontend Angular", "Angular", "Módulo de interfaz que consume la API de categorías", $sprite="angular")
        Container(pusher, "Pusher (Eventos)", "Servicio externo", "Emite notificaciones en tiempo real cuando cambian las categorías.", $sprite="cube")
    }
}

BiRel_D(api, bd, "", "Consulta los datos de categorías en la base de datos")
Rel_R(app2, app, "", "El usuario interactúa con el módulo de categorías desde la página web")
BiRel_R(app, c2, "Interactúa con el módulo de categorías", "")
BiRel_D(angular, html, "Renderiza vistas de categorías", "")
BiRel_D(angular, api, "", "Angular solicita y envía datos de categorías al API")
Rel_D(api, c3, "Invoca endpoints de categorías", "")
BiRel_U(pusher, c3, "Notifica cambios", "")

@enduml
